import dotenv from 'dotenv';
import mongoose from 'mongoose';
import { RewardOffer } from '../app/RewardOffer/rewardOffer.model';
import { connectSeedDb, upsertByKey } from './seedUtils';

dotenv.config();

const ACTIVE_REWARD_OFFER_SLUGS = new Set([
  'total-deposit-platinum-25000',
  'total-deposit-gold-10000',
  'night-owl-18',
  'vip-club-150',
  'cashback-king-45',
  'refer-legend-10',
  'refer-1-friend',
  'refer-3-friends',
]);

const REWARD_OFFERS = [
  {
    slug: 'member-bonus-10',
    title: {
      en: 'Member Bonus ৳10',
      bn: 'মেম্বার বোনাস ৳১০',
      hi: 'सदस्य बोनस ৳10',
    },
    description: {
      en: 'Claim ৳10 every 15 days (1× turnover)',
      bn: 'প্রতি ১৫ দিনে ৳১০ ক্লেইম (১× টার্নওভার)',
      hi: 'हर 15 दिन में ৳10 क्लेम (1× टर्नओवर)',
    },
    bonusAmount: 10,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 1,
    isActive: true,
  },
  {
    slug: 'daily-login-5',
    title: {
      en: 'Daily Login Bonus',
      bn: 'দৈনিক লগইন বোনাস',
      hi: 'दैनिक लॉगिन बोनस',
    },
    description: {
      en: 'Claim ৳5 every 24 hours',
      bn: 'প্রতি ২৪ ঘণ্টায় ৳৫ ক্লেইম',
      hi: 'हर 24 घंटे में ৳5 क्लेम',
    },
    bonusAmount: 5,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 2,
    isActive: true,
  },
  {
    slug: 'daily-deposit-100',
    title: {
      en: 'Daily Deposit ৳100',
      bn: 'দৈনিক ডিপোজিট ৳১০০',
      hi: 'दैनिक जमा ৳100',
    },
    description: {
      en: 'Deposit ৳100 today to claim ৳15',
      bn: 'আজ ৳১০০ ডিপোজিট করে ৳১৫ ক্লেইম করুন',
      hi: 'आज ৳100 जमा करके ৳15 क्लेम करें',
    },
    bonusAmount: 15,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 100,
    sortOrder: 3,
    isActive: true,
  },
  {
    slug: 'daily-deposit-300',
    title: {
      en: 'Daily Deposit ৳300',
      bn: 'দৈনিক ডিপোজিট ৳৩০০',
      hi: 'दैनिक जमा ৳300',
    },
    description: {
      en: 'Deposit ৳300 today to claim ৳50',
      bn: 'আজ ৳৩০০ ডিপোজিট করে ৳৫০ ক্লেইম করুন',
      hi: 'आज ৳300 जमा करके ৳50 क्लेम करें',
    },
    bonusAmount: 50,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 300,
    sortOrder: 4,
    isActive: true,
  },
  {
    slug: 'daily-deposit-1000',
    title: {
      en: 'Daily Deposit ৳1000',
      bn: 'দৈনিক ডিপোজিট ৳১০০০',
      hi: 'दैनिक जमा ৳1000',
    },
    description: {
      en: 'Deposit ৳1000 today to claim ৳150',
      bn: 'আজ ৳১০০০ ডিপোজিট করে ৳১৫০ ক্লেইম করুন',
      hi: 'आज ৳1000 जमा करके ৳150 क्लेम करें',
    },
    bonusAmount: 150,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 1000,
    sortOrder: 5,
    isActive: true,
  },
  {
    slug: 'weekend-bonus-20',
    title: {
      en: 'Weekend Bonus',
      bn: 'সাপ্তাহিক ছুটির বোনাস',
      hi: 'सप्ताहांत बोनस',
    },
    description: {
      en: 'Claim ৳20 every 3 days',
      bn: 'প্রতি ৩ দিনে ৳২০ ক্লেইম',
      hi: 'हर 3 दिन में ৳20 क्लेम',
    },
    bonusAmount: 20,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 6,
    isActive: true,
  },
  {
    slug: 'loyalty-bonus-12',
    title: {
      en: 'Loyalty Bonus',
      bn: 'লয়্যালটি বোনাস',
      hi: 'लॉयल्टी बोनस',
    },
    description: {
      en: 'Claim ৳12 every 3 days',
      bn: 'প্রতি ৩ দিনে ৳১২ ক্লেইম',
      hi: 'हर 3 दिन में ৳12 क्लेम',
    },
    bonusAmount: 12,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 7,
    isActive: true,
  },
  {
    slug: 'weekly-bonus-25',
    title: {
      en: 'Weekly Bonus',
      bn: 'সাপ্তাহিক বোনাস',
      hi: 'साप्ताहिक बोनस',
    },
    description: {
      en: 'Claim ৳25 every 7 days',
      bn: 'প্রতি ৭ দিনে ৳২৫ ক্লেইম',
      hi: 'हर 7 दिन में ৳25 क्लेम',
    },
    bonusAmount: 25,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 8,
    isActive: true,
  },
  {
    slug: 'biweekly-bonus-40',
    title: {
      en: 'Bi-weekly Bonus',
      bn: 'পাক্ষিক বোনাস',
      hi: 'पाक्षिक बोनस',
    },
    description: {
      en: 'Claim ৳40 every 15 days',
      bn: 'প্রতি ১৫ দিনে ৳৪০ ক্লেইম',
      hi: 'हर 15 दिन में ৳40 क्लेम',
    },
    bonusAmount: 40,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 9,
    isActive: true,
  },
  {
    slug: 'refer-1-friend',
    title: {
      en: 'Refer 1 Friend',
      bn: '১ জন বন্ধুকে রেফার করুন',
      hi: '1 मित्र को रेफर करें',
    },
    description: {
      en: 'Refer at least 1 friend to claim ৳100',
      bn: 'কমপক্ষে ১ জন বন্ধুকে রেফার করে ৳১০০ ক্লেইম করুন',
      hi: 'कम से कम 1 मित्र रेफर करके ৳100 क्लेम करें',
    },
    bonusAmount: 100,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'referral',
    criteriaValue: 1,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: 'refer-3-friends',
    title: {
      en: 'Refer 3 Friends',
      bn: '৩ জন বন্ধুকে রেফার করুন',
      hi: '3 मित्रों को रेफर करें',
    },
    description: {
      en: 'Refer at least 3 friends to claim ৳300',
      bn: 'কমপক্ষে ৩ জন বন্ধুকে রেফার করে ৳৩০০ ক্লেইম করুন',
      hi: 'कम से कम 3 मित्र रेफर करके ৳300 क्लेम करें',
    },
    bonusAmount: 300,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'referral',
    criteriaValue: 3,
    sortOrder: 11,
    isActive: true,
  },
  {
    slug: 'refer-5-friends',
    title: {
      en: 'Refer 5 Friends',
      bn: '৫ জন বন্ধুকে রেফার করুন',
      hi: '5 मित्रों को रेफर करें',
    },
    description: {
      en: 'Refer at least 5 friends to claim ৳500',
      bn: 'কমপক্ষে ৫ জন বন্ধুকে রেফার করে ৳৫০০ ক্লেইম করুন',
      hi: 'कम से कम 5 मित्र रेफर करके ৳500 क्लेम करें',
    },
    bonusAmount: 500,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'referral',
    criteriaValue: 5,
    sortOrder: 12,
    isActive: true,
  },
  {
    slug: 'first-week-500',
    title: {
      en: 'First Week Bonus',
      bn: 'প্রথম সপ্তাহের বোনাস',
      hi: 'पहले सप्ताह का बोनस',
    },
    description: {
      en: 'Total deposit ৳500+ to claim ৳30',
      bn: 'মোট ৳৫০০+ ডিপোজিট করে ৳৩০ ক্লেইম করুন',
      hi: 'कुल ৳500+ जमा करके ৳30 क्लेम करें',
    },
    bonusAmount: 30,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'total_deposit',
    criteriaValue: 500,
    sortOrder: 13,
    isActive: true,
  },
  {
    slug: 'high-roller-5000',
    title: {
      en: 'High Roller Bonus',
      bn: 'হাই রোলার বোনাস',
      hi: 'हाई रोलर बोनस',
    },
    description: {
      en: 'Total deposit ৳5000+ to claim ৳200',
      bn: 'মোট ৳৫০০০+ ডিপোজিট করে ৳২০০ ক্লেইম করুন',
      hi: 'कुल ৳5000+ जमा करके ৳200 क्लेम करें',
    },
    bonusAmount: 200,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'total_deposit',
    criteriaValue: 5000,
    sortOrder: 14,
    isActive: true,
  },
  {
    slug: 'mega-daily-1000',
    title: {
      en: 'Mega Daily Bonus',
      bn: 'মেগা দৈনিক বোনাস',
      hi: 'मेगा दैनिक बोनस',
    },
    description: {
      en: 'Deposit ৳1000 today to claim ৳77',
      bn: 'আজ ৳১০০০ ডিপোজিট করে ৳৭৭ ক্লেইম করুন',
      hi: 'आज ৳1000 जमा करके ৳77 क्लेम करें',
    },
    bonusAmount: 77,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 1000,
    sortOrder: 15,
    isActive: true,
  },
  // ── 25 creative offers (sortOrder 16–40) ──
  {
    slug: 'lucky-spin-7',
    title: {
      en: 'Lucky Spin ৳7',
      bn: 'লাকি স্পিন ৳৭',
      hi: 'लकी स्पिन ৳7',
    },
    description: {
      en: 'Spin into luck — claim ৳7 every day',
      bn: 'ভাগ্যের স্পিন — প্রতিদিন ৳৭ ক্লেইম করুন',
      hi: 'किस्मत का स्पिन — रोज ৳7 क्लेम करें',
    },
    bonusAmount: 7,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 16,
    isActive: true,
  },
  {
    slug: 'cricket-matchday-33',
    title: {
      en: 'Cricket Matchday ৳33',
      bn: 'ক্রিকেট ম্যাচডে ৳৩৩',
      hi: 'क्रिकेट मैचडे ৳33',
    },
    description: {
      en: 'Match day special — claim ৳33 every 3 days',
      bn: 'ম্যাচডে স্পেশাল — প্রতি ৩ দিনে ৳৩৩',
      hi: 'मैच डे स्पेशल — हर 3 दिन ৳33',
    },
    bonusAmount: 33,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 17,
    isActive: true,
  },
  {
    slug: 'slot-champion-88',
    title: {
      en: 'Slot Champion ৳88',
      bn: 'স্লট চ্যাম্পিয়ন ৳৮৮',
      hi: 'स्लॉट चैंपियन ৳88',
    },
    description: {
      en: 'For slot lovers — ৳88 weekly reward',
      bn: 'স্লট প্রেমীদের জন্য — সাপ্তাহিক ৳৮৮',
      hi: 'स्लॉट प्रेमियों के लिए — साप्ताहिक ৳88',
    },
    bonusAmount: 88,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 18,
    isActive: true,
  },
  {
    slug: 'fortune-777',
    title: {
      en: 'Fortune 777',
      bn: 'ফরচুন ৭৭৭',
      hi: 'फॉर्च्यून 777',
    },
    description: {
      en: 'Lucky 777 — claim ৳77 every 7 days',
      bn: 'লাকি ৭৭৭ — প্রতি ৭ দিনে ৳৭৭',
      hi: 'लकी 777 — हर 7 दिन ৳77',
    },
    bonusAmount: 77,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 19,
    isActive: true,
  },
  {
    slug: 'night-owl-18',
    title: {
      en: 'Night Owl Bonus',
      bn: 'নাইট আউল বোনাস',
      hi: 'नाइट आउल बोनस',
    },
    description: {
      en: 'Night players reward — ৳18 every 24 hours',
      bn: 'রাতের খেলোয়াড়দের জন্য — ৳১৮ প্রতি ২৪ ঘণ্টা',
      hi: 'रात के खिलाड़ियों के लिए — ৳18 हर 24 घंटे',
    },
    bonusAmount: 18,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: 'early-bird-22',
    title: {
      en: 'Early Bird Bonus',
      bn: 'আর্লি বার্ড বোনাস',
      hi: 'अर्ली बर्ड बोनस',
    },
    description: {
      en: 'Rise and claim — ৳22 every 24 hours',
      bn: 'সকালে উঠে ক্লেইম — ৳২২ প্রতি ২৪ ঘণ্টা',
      hi: 'सुबह उठकर क्लेम — ৳22 हर 24 घंटे',
    },
    bonusAmount: 22,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 21,
    isActive: true,
  },
  {
    slug: 'vip-club-150',
    title: {
      en: 'VIP Club Reward',
      bn: 'ভিআইপি ক্লাব রিওয়ার্ড',
      hi: 'VIP क्लब रिवॉर्ड',
    },
    description: {
      en: 'VIP exclusive — ৳150 every 15 days',
      bn: 'ভিআইপি এক্সক্লুসিভ — ৳১৫০ প্রতি ১৫ দিন',
      hi: 'VIP एक्सक्लूसिव — ৳150 हर 15 दिन',
    },
    bonusAmount: 150,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 22,
    isActive: true,
  },
  {
    slug: 'cashback-king-45',
    title: {
      en: 'Cashback King ৳45',
      bn: 'ক্যাশব্যাক কিং ৳৪৫',
      hi: 'कैशबैक किंग ৳45',
    },
    description: {
      en: 'Weekly cashback style bonus — ৳45',
      bn: 'সাপ্তাহিক ক্যাশব্যাক স্টাইল — ৳৪৫',
      hi: 'साप्ताहिक कैशबैक स्टाइल — ৳45',
    },
    bonusAmount: 45,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 23,
    isActive: true,
  },
  {
    slug: 'deposit-starter-50',
    title: {
      en: 'Starter Deposit Boost',
      bn: 'স্টার্টার ডিপোজিট বুস্ট',
      hi: 'स्टार्टर जमा बूस्ट',
    },
    description: {
      en: 'Deposit ৳50 today → claim ৳8',
      bn: 'আজ ৳৫০ ডিপোজিট → ৳৮ ক্লেইম',
      hi: 'आज ৳50 जमा → ৳8 क्लेम',
    },
    bonusAmount: 8,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 50,
    sortOrder: 24,
    isActive: true,
  },
  {
    slug: 'deposit-power-200',
    title: {
      en: 'Power Deposit ৳200',
      bn: 'পাওয়ার ডিপোজিট ৳২০০',
      hi: 'पावर जमा ৳200',
    },
    description: {
      en: 'Deposit ৳200 today → claim ৳35',
      bn: 'আজ ৳২০০ ডিপোজিট → ৳৩৫ ক্লেইম',
      hi: 'आज ৳200 जमा → ৳35 क्लेम',
    },
    bonusAmount: 35,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 200,
    sortOrder: 25,
    isActive: true,
  },
  {
    slug: 'deposit-elite-500',
    title: {
      en: 'Elite Deposit ৳500',
      bn: 'এলিট ডিপোজিট ৳৫০০',
      hi: 'एलीट जमा ৳500',
    },
    description: {
      en: 'Deposit ৳500 today → claim ৳80',
      bn: 'আজ ৳৫০০ ডিপোজিট → ৳৮০ ক্লেইম',
      hi: 'आज ৳500 जमा → ৳80 क्लेम',
    },
    bonusAmount: 80,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 500,
    sortOrder: 26,
    isActive: true,
  },
  {
    slug: 'deposit-whale-2000',
    title: {
      en: 'Whale Deposit ৳2000',
      bn: 'হোয়েল ডিপোজিট ৳২০০০',
      hi: 'व्हेल जमा ৳2000',
    },
    description: {
      en: 'Deposit ৳2000 today → claim ৳250',
      bn: 'আজ ৳২০০০ ডিপোজিট → ৳২৫০ ক্লেইম',
      hi: 'आज ৳2000 जमा → ৳250 क्लेम',
    },
    bonusAmount: 250,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 2000,
    sortOrder: 27,
    isActive: true,
  },
  {
    slug: 'deposit-midnight-150',
    title: {
      en: 'Midnight Deposit Rush',
      bn: 'মিডনাইট ডিপোজিট রাশ',
      hi: 'मिडनाइट जमा रश',
    },
    description: {
      en: 'Deposit ৳150 today → claim ৳25',
      bn: 'আজ ৳১৫০ ডিপোজিট → ৳২৫ ক্লেইম',
      hi: 'आज ৳150 जमा → ৳25 क्लेम',
    },
    bonusAmount: 25,
    turnoverMultiplier: 1,
    cooldownHours: 24,
    criteriaType: 'daily_deposit',
    criteriaValue: 150,
    sortOrder: 28,
    isActive: true,
  },
  {
    slug: 'refer-squad-2',
    title: {
      en: 'Squad Builder (2 Referrals)',
      bn: 'স্কোয়াড বিল্ডার (২ রেফারেল)',
      hi: 'स्क्वाड बिल्डर (2 रेफरल)',
    },
    description: {
      en: 'Bring 2 friends → claim ৳150',
      bn: '২ জন বন্ধু আনুন → ৳১৫০ ক্লেইম',
      hi: '2 दोस्त लाएं → ৳150 क्लेम',
    },
    bonusAmount: 150,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'referral',
    criteriaValue: 2,
    sortOrder: 29,
    isActive: true,
  },
  {
    slug: 'refer-legend-10',
    title: {
      en: 'Referral Legend (10 Friends)',
      bn: 'রেফারেল লিজেন্ড (১০ বন্ধু)',
      hi: 'रेफरल लीजेंड (10 मित्र)',
    },
    description: {
      en: 'Refer 10 friends → claim ৳1000',
      bn: '১০ জন বন্ধু রেফার → ৳১০০০ ক্লেইম',
      hi: '10 मित्र रेफर → ৳1000 क्लेम',
    },
    bonusAmount: 1000,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'referral',
    criteriaValue: 10,
    sortOrder: 30,
    isActive: true,
  },
  {
    slug: 'refer-champion-7',
    title: {
      en: 'Referral Champion (7 Friends)',
      bn: 'রেফারেল চ্যাম্পিয়ন (৭ বন্ধু)',
      hi: 'रेफरल चैंपियन (7 मित्र)',
    },
    description: {
      en: 'Refer 7 friends → claim ৳700',
      bn: '৭ জন বন্ধু রেফার → ৳৭০০ ক্লেইম',
      hi: '7 मित्र रेफर → ৳700 क्लेम',
    },
    bonusAmount: 700,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'referral',
    criteriaValue: 7,
    sortOrder: 31,
    isActive: true,
  },
  {
    slug: 'total-deposit-bronze-1000',
    title: {
      en: 'Bronze Milestone ৳1000',
      bn: 'ব্রোঞ্জ মাইলস্টোন ৳১০০০',
      hi: 'ब्रॉन्ज माइलस्टोन ৳1000',
    },
    description: {
      en: 'Lifetime deposit ৳1000+ → claim ৳50',
      bn: 'মোট ৳১০০০+ ডিপোজিট → ৳৫০ ক্লেইম',
      hi: 'कुल ৳1000+ जमा → ৳50 क्लेम',
    },
    bonusAmount: 50,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'total_deposit',
    criteriaValue: 1000,
    sortOrder: 32,
    isActive: true,
  },
  {
    slug: 'total-deposit-silver-2500',
    title: {
      en: 'Silver Milestone ৳2500',
      bn: 'সিলভার মাইলস্টোন ৳২৫০০',
      hi: 'सिल्वर माइलस्टोन ৳2500',
    },
    description: {
      en: 'Lifetime deposit ৳2500+ → claim ৳120',
      bn: 'মোট ৳২৫০০+ ডিপোজিট → ৳১২০ ক্লেইম',
      hi: 'कुल ৳2500+ जमा → ৳120 क्लेम',
    },
    bonusAmount: 120,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'total_deposit',
    criteriaValue: 2500,
    sortOrder: 33,
    isActive: true,
  },
  {
    slug: 'total-deposit-gold-10000',
    title: {
      en: 'Gold Milestone ৳10000',
      bn: 'গোল্ড মাইলস্টোন ৳১০০০০',
      hi: 'गोल्ड माइलस्टोन ৳10000',
    },
    description: {
      en: 'Lifetime deposit ৳10000+ → claim ৳500',
      bn: 'মোট ৳১০০০০+ ডিপোজিট → ৳৫০০ ক্লেইম',
      hi: 'कुल ৳10000+ जमा → ৳500 क्लेम',
    },
    bonusAmount: 500,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'total_deposit',
    criteriaValue: 10000,
    sortOrder: 34,
    isActive: true,
  },
  {
    slug: 'total-deposit-platinum-25000',
    title: {
      en: 'Platinum Elite ৳25000',
      bn: 'প্ল্যাটিনাম এলিট ৳২৫০০০',
      hi: 'प्लैटिनम एलीट ৳25000',
    },
    description: {
      en: 'Lifetime deposit ৳25000+ → claim ৳1200',
      bn: 'মোট ৳২৫০০০+ ডিপোজিট → ৳১২০০ ক্লেইম',
      hi: 'कुल ৳25000+ जमा → ৳1200 क्लेम',
    },
    bonusAmount: 1200,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'total_deposit',
    criteriaValue: 25000,
    sortOrder: 35,
    isActive: true,
  },
  {
    slug: 'fishing-frenzy-55',
    title: {
      en: 'Fishing Frenzy ৳55',
      bn: 'ফিশিং ফ্রেনজি ৳৫৫',
      hi: 'फिशिंग फ्रेंजी ৳55',
    },
    description: {
      en: 'Catch the reward — ৳55 every 3 days',
      bn: 'পুরস্কার ধরুন — ৳৫৫ প্রতি ৩ দিন',
      hi: 'इनाम पकड़ें — ৳55 हर 3 दिन',
    },
    bonusAmount: 55,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 36,
    isActive: true,
  },
  {
    slug: 'aviator-pilot-66',
    title: {
      en: 'Aviator Pilot Bonus',
      bn: 'এভিয়েটর পাইলট বোনাস',
      hi: 'एविएटर पायलट बोनस',
    },
    description: {
      en: 'Fly high — claim ৳66 every 3 days',
      bn: 'উড়ে যান — ৳৬৬ প্রতি ৩ দিনে ক্লেইম',
      hi: 'ऊंची उड़ान — ৳66 हर 3 दिन',
    },
    bonusAmount: 66,
    turnoverMultiplier: 1,
    cooldownHours: 72,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 37,
    isActive: true,
  },
  {
    slug: 'baccarat-royale-99',
    title: {
      en: 'Baccarat Royale ৳99',
      bn: 'ব্যাকারাট রয়্যাল ৳৯৯',
      hi: 'बैकारेट रॉयल ৳99',
    },
    description: {
      en: 'Live casino royalty — ৳99 weekly',
      bn: 'লাইভ ক্যাসিনো রয়্যালটি — সাপ্তাহিক ৳৯৯',
      hi: 'लाइव कैसीनो रॉयल्टी — साप्ताहिक ৳99',
    },
    bonusAmount: 99,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 38,
    isActive: true,
  },
  {
    slug: 'streak-master-111',
    title: {
      en: 'Streak Master ৳111',
      bn: 'স্ট্রিক মাস্টার ৳১১১',
      hi: 'स्ट्रीक मास्टर ৳111',
    },
    description: {
      en: 'Keep the streak — ৳111 every 7 days',
      bn: 'স্ট্রিক ধরে রাখুন — ৳১১১ প্রতি ৭ দিন',
      hi: 'स्ट्रीक बनाए रखें — ৳111 हर 7 दिन',
    },
    bonusAmount: 111,
    turnoverMultiplier: 1,
    cooldownHours: 168,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 39,
    isActive: true,
  },
  {
    slug: 'grand-jackpot-222',
    title: {
      en: 'Grand Jackpot ৳222',
      bn: 'গ্র্যান্ড জ্যাকপট ৳২২২',
      hi: 'ग्रैंड जैकपॉट ৳222',
    },
    description: {
      en: 'Ultimate reward — ৳222 every 15 days',
      bn: 'চূড়ান্ত পুরস্কার — ৳২২২ প্রতি ১৫ দিন',
      hi: 'अल्टीमेट इनाम — ৳222 हर 15 दिन',
    },
    bonusAmount: 222,
    turnoverMultiplier: 1,
    cooldownHours: 360,
    criteriaType: 'none',
    criteriaValue: 0,
    sortOrder: 40,
    isActive: true,
  },
];

async function main() {
  await connectSeedDb();
  const offers = REWARD_OFFERS.map((offer) => ({
    ...offer,
    isActive: ACTIVE_REWARD_OFFER_SLUGS.has(offer.slug),
  }));
  const count = await upsertByKey(
    RewardOffer as mongoose.Model<unknown>,
    'slug',
    offers,
  );
  const activeCount = offers.filter((offer) => offer.isActive).length;
  console.log(
    `✅ Seeded ${count} reward offers (${offers.length} total, ${activeCount} active)`,
  );
  process.exit(0);
}

main().catch((err) => {
  console.error('❌ seedRewardOffers failed:', err);
  process.exit(1);
});
